[package]
name = "fire-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "./bin/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.20"
winit = { version = "0.28.0"}
wgpu = { version = "0.17"}
env_logger = "0.10.1"
pollster = "0.3.0"
