[package]
name = "wall-e-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "wall_e_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.0", features = ["multiple-pymethods"] }
wall-e = { path = "../wall-e" }
nalgebra = "0.32.3"
wall-e-py-macros = { path = "../wall-e-py-macros" }
